export const SEO_PENALTIES = {
  // Title penalties
  TITLE_MISSING: 25,
  TITLE_TOO_SHORT: 10,
  TITLE_TOO_LONG: 5,
  
  // Description penalties
  DESCRIPTION_MISSING: 20,
  DESCRIPTION_TOO_SHORT: 8,
  DESCRIPTION_TOO_LONG: 5,
  
  // Heading penalties
  H1_MISSING: 15,
  H1_MULTIPLE: 5,
  HEADING_HIERARCHY_VIOLATION: 2,
  
  // Technical penalties
  NO_HTTPS: 20,
  NO_CANONICAL: 5,
  NO_SCHEMA: 5,
  NO_ROBOTS_TXT: 10,
  ROBOTS_BLOCKS_ALL: 25,
  NO_SITEMAP: 15,
  EMPTY_SITEMAP: 10,
  
  // Content penalties
  NO_META_KEYWORDS: 3,
  INVALID_META_KEYWORDS: 2,
  NO_KEYWORDS_FOUND: 10,
  POOR_KEYWORD_OPTIMIZATION: 8,
  BASIC_KEYWORD_OPTIMIZATION: 5,
  GOOD_KEYWORD_OPTIMIZATION: 2,
  
  // Symbol and emoji penalties
  TITLE_EMOJI: 3,
  DESCRIPTION_EMOJI: 2,
  TITLE_SYMBOLS_BASE: 1,
  TITLE_SYMBOLS_PER_PAIR: 0.5,
  DESCRIPTION_SYMBOLS_BASE: 1,
  DESCRIPTION_SYMBOLS_PER_TRIO: 0.33,
  
  // Image penalties
  IMAGE_NO_ALT_PER_PAIR: 0.5,
  IMAGE_OPTIMIZATION_MULTIPLIER: 0.4,
  
  // Keyword stuffing penalties
  KEYWORD_STUFFING_PER_ISSUE: 3
} as const satisfies Record<string, number>;

export const SEO_SCORING_LIMITS = {
  MIN_SCORE: 0,
  MAX_SCORE: 100,
  MAX_KEYWORD_PENALTY: 25,
  MAX_IMAGE_ALT_PENALTY: 7,
  MAX_TITLE_SYMBOLS_PENALTY: 5,
  MAX_DESCRIPTION_SYMBOLS_PENALTY: 3
} as const satisfies Record<string, number>;

export const SEO_THRESHOLDS = {
  TITLE_MIN_LENGTH: 30,
  TITLE_MAX_LENGTH: 60,
  DESCRIPTION_MIN_LENGTH: 120,
  DESCRIPTION_MAX_LENGTH: 160,
  MAX_KEYWORDS_RECOMMENDED: 5,
  PAGE_SIZE_LIMIT: 5000000, // 5MB
  INTERNAL_URLS_LIMIT: 100
} as const satisfies Record<string, number>;

export const KEYWORD_SCORING = {
  MAX_KEYWORD_SCORE: 25,
  MIN_OPTIMIZATION_THRESHOLD: 10,
  GOOD_OPTIMIZATION_THRESHOLD: 20
} as const satisfies Record<string, number>;